version: '2.1'

services:
  lau-case-backend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/spring-boot/template
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - $SERVER_PORT:$SERVER_PORT

  lau-case-database:
    container_name: lau-case-database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${LAU_DB_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${LAU_DB_ADMIN_PASSWORD}
      POSTGRES_DB: ${LAU_DB_NAME}
    ports:
      - 5054:5432
    volumes:
      - lau-database-data:/var/lib/postgresql/data

volumes:
  lau-database-data:
