server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: Case Log and Audit
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://lau-case-backend-aat.postgres.database.azure.com:5432/${LAU_DB_NAME:lau_case}${LAU_DB_CONN_OPTIONS:}
    username: lauadmin@lau-case-backend-aat
    password: I&?>3r=2t9[IF)Hs
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 20
      idleTimeout: 10000
      poolName: LAUCaseHikariCP
      maxLifetime: 7200000
      connectionTimeout: 60000
  #    tomcat:
  #      max-active: 10
  #      max-idle: 10
  #      min-idle: 2
  #      max-wait: 10000
  #      test-on-borrow: true
  #      test-on-connect: true
  #      test-on-idle: true
  #      validation-query: "SELECT 1"
  #      time-between-eviction-runs-millis: 10000
  #      test-while-idle: true
  #      test-on-return: true
  #      remove-abandoned: true
  #      remove-abandoned-timeout: 60
  #      log-abandoned: true
  #      abandon-when-percentage-full: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
    show-sql: true
  flyway:
    enabled: false
    user: ${LAU_DB_ADMIN_USERNAME:lauadmin}
    password: ${LAU_DB_ADMIN_PASSWORD:}
    placeholders:
      LAU_DB_PASSWORD: ${LAU_DB_PASSWORD:}

idam:
  s2s-auth:
    url: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
  api:
    url: https://idam-api.aat.platform.hmcts.net
  client:
    id: ${IDAM_CLIENT_NAME:lau}
    secret: gQ4pHYQ8TTYdQp8d
    redirect_uri: https://lau-case.aat.platform.hmcts.net/oauth2/callback

authorised.services: lau_frontend,ccd_data
authorised.roles: cft-audit-investigator
db.allow.delete.record: ${DB_ALLOW_DELETE_RECORD:true}

azure:
  application-insights:
    instrumentation-key: ${lau.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

flyway:
  noop:
    strategy: "false"

default.page.size: ${LAU_PAGE_SIZE_DEFAULT:10000}