---
version: '3'

services:
  sidam-api:
    image: "hmctspublic.azurecr.io/idam/api:stable"
    environment:
      JAVA_OPTS: -Xms128m -Xmx512m -Dlogging.level.uk.gov.hmcts=INFO
      TESTING_SUPPORT_ENABLED: "true"
      IDAMHEALTHCHECK_AM_ENABLED: "false"
      IDAMHEALTHCHECK_IDM_ENABLED: "false"
      STRATEGIC_ADMIN_URL: http://idam-web-admin:8082
      STRATEGIC_WEBPUBLIC_URL: http://idam-web-public:3501
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://shared-db:5432/openidm?currentSchema=fridam
      SPRING_DATASOURCE_USERNAME: openidm
      SPRING_DATASOURCE_PASSWORD: openidm
      SPRING_DATA_ELASTICSEARCH_PROPERTIES_PATH_HOME: /tmp/es
      SECURITY_OAUTH2_CLIENT_CLIENTSECRET: password
      SECURITY_OAUTH2_CLIENT_PRE_ESTABLISHED_REDIRECT_URI: http://idam-web-public:3501/login
      SECURITY_OAUTH2_CLIENT_REGISTERED_REDIRECT_URI: http://idam-web-public:3501/login
      IDAM_SPI_FORGEROCK_AM_ROOT: http://fr-am:8080/openam
      IDAM_SPI_FORGEROCK_AM_TOPLEVELHOST: fr-am
      IDAM_SPI_FORGEROCK_AM_USERNAME: amadmin
      IDAM_SPI_FORGEROCK_AM_PASSWORD: Pa55word11
      IDAM_SPI_FORGEROCK_AM_JWKSURIFOROAUTH2CLIENTS: http://fr-am:8080/openam/oauth2/hmcts/connect/jwk_uri
      IDAM_SPI_FORGEROCK_IDM_ROOT: http://fr-idm:18080/openidm
      IDAM_SPI_FORGEROCK_IDM_USERNAME: openidm-admin
      IDAM_SPI_FORGEROCK_IDM_PASSWORD: openidm-admin
      APPSETTING_NODE_PATH: es/
    ports:
      - 5000:5000
    links:
      - fr-am
      - fr-idm
      - shared-db
    depends_on:
      - fr-am
      - fr-idm
      - shared-db

  service-auth-provider-api:
    image: "hmctspublic.azurecr.io/rpe/service-auth-provider:latest"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      MICROSERVICEKEYS_CCD_DATA: "${IDAM_KEY_CCD_DATA_STORE}"
      MICROSERVICEKEYS_CCD_GW: "${IDAM_KEY_CCD_GATEWAY}"
      MICROSERVICEKEYS_CCD_DEFINITION: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      MICROSERVICEKEYS_CCD_ADMIN: "${IDAM_KEY_CCD_ADMIN}"
      MICROSERVICEKEYS_FPL_CASE_SERVICE: "${IDAM_KEY_FPL_CASE_SERVICE}"
      MICROSERVICEKEYS_EM_GW: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_BULK_SCAN_PROCESSOR: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_BULK_SCAN_PROCESSOR_TESTS: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_BULK_SCAN_ORCHESTRATOR: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_PROBATE_BACKEND: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_PROBATE_FRONTEND: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_DG_DOCASSEMBLY_API: "AAAAAAAAAAAAAAAA"
      MICROSERVICE_KEYS_RPA_DG_DOCASSEMBLY: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_PCQ_CONSOLIDATION_SERVICE: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_LAU_FRONTEND: "AAAAAAAAAAAAAAAA"
      TESTING_SUPPORT_ENABLED: "true"
    ports:
      - 4502:8080

  fr-am:
    image: "hmctsprivate.azurecr.io/idam/idam-fr-am:latest"
    environment:
      JAVA_OPTS: -Xms128m -Xmx512m
    ports:
      - 8080:8080
      - 1389:1389
    depends_on:
      - shared-db

  fr-idm:
    image: "hmctsprivate.azurecr.io/idam/idam-fr-idm:latest"
    environment:
      JAVA_TOOL_OPTIONS: -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=vm-ubuntu16 -Dcom.sun.management.jmxremote.rmi.port=9010
      JAVA_OPTS: -Xms128m -Xmx512m
    ports:
      - 18080:18080
      - 9010:9010
    depends_on:
      - fr-am
      - shared-db

  shared-db:
    image: "hmctsprivate.azurecr.io/idam/shared-db:latest"
    ports:
      - 5051:5432

