---
version: '3'

services:
  idam-web-admin:
    image: "hmctspublic.azurecr.io/idam/web-admin:stable"
    environment:
      JAVA_OPTS: -Xms128m -Xmx512m
      STRATEGIC_SERVICE_URL: http://sidam-api:5000
    ports:
      - 8082:8080
    links:
      - sidam-api
    depends_on:
      - sidam-api

  idam-web-public:
    image: "hmctspublic.azurecr.io/idam/web-public:stable"
    environment:
     STRATEGIC_SERVICE_URL: http://sidam-api:5000
     IDAM_CONTINUE_URL_VALIDATOR_ENFORCE_TLS: "false"
     REFORM_SERVICE_NAME: sidam-api
     REFORM_TEAM: idam
     REFORM_ENVIRONMENT: local
     JAVA_OPTS: -Xms128m -Xmx512m
    ports:
      - 3501:8080
    links:
      - sidam-api
    depends_on:
      - sidam-api

