java:
  environment:
    LAU_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
    LAU_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
    LAU_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword }}"
    LAU_DB_HOST: "{{ .Release.Name }}-postgresql"
    LAU_DB_PORT: "5432"
    FLYWAY_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase }}"
    FLYWAY_USER: "{{ .Values.postgresql.postgresqlUsername }}"
    FLYWAY_PASSWORD: "{{ .Values.postgresql.postgresqlPassword }}"
    FLYWAY_NOOP_STRATEGY: "false"
    DB_ENCRYPTION_ENABLED: "No"
    TEST_S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

  postgresql:
    enabled: true
    postgresqlUsername: lauadmin
    postgresqlPassword: laupass
    postgresqlDatabase: lau_case
