java:
  memoryRequests: "1024Mi"
  cpuRequests: "500m"
  memoryLimits: "2048Mi"
  cpuLimits: "1500m"
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/lau/case-backend:latest'
  ingressHost: lau-case-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: lau
  environment:
    LAU_DB_NAME: lau_case
    LAU_DB_HOST: lau-case-backend-{{ .Values.global.environment }}.postgres.database.azure.com
    LAU_DB_PORT: "5432"
    FLYWAY_URL: jdbc:postgresql://lau-case-backend-{{ .Values.global.environment }}.postgres.database.azure.com:5432/lau_case?sslmode=require
    FLYWAY_USER: lauadmin@lau-case-backend-{{ .Values.global.environment }}
    FLYWAY_NOOP_STRATEGY: "false"
    LAU_DB_CONN_OPTIONS: "?sslmode=require"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    IDAM_CLIENT_REDIRECT_URI: "https://lau-case-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
    IDAM_CLIENT_NAME: 'lau'
    DB_ALLOW_DELETE_RECORD: "false"
  keyVaults:
    lau:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: case-backend-POSTGRES-PASS
          alias: spring.flyway.password
        - name: case-backend-POSTGRES-USER
          alias: spring.flyway.user
        - name: case-backend-app-db-password
          alias: spring.datasource.password
        - name: case-backend-app-db-password
          alias: spring.flyway.placeholders.LAU_DB_PASSWORD
        - name: case-backend-app-db-user
          alias: spring.datasource.username
        - name: flyway-password
          alias: flyway.password
        - name: idam-client-secret
          alias: idam.client.secret


